name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
        working-directory: package
      - run: yarn lint
        working-directory: package
      - run: yarn build
        working-directory: package
      - run: yarn publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}