# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue it`s being marked as stale and will be automatically closed after 7 more days without any activity.'
        stale-pr-message: 'This PR it`s being marked as stale and will be automatically closed after 7 more days without any activity.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
